image: python:3

before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass

stages: 
    - build
    - deploy

build:
    stage: build
    script:
        - pip install --no-cache-dir -r docker/requirements.txt

deploy:
    stage: deploy
    script:
        # Setup Production Environment
        - mv app/.env.example app/.env
        - sed -i "s/:HOST/172.20.0.2/g" app/.env
        - sed -i "s/:USER/root/g" app/.env
        - sed -i "s/:PASSWORD/$DB_PASS/g" app/.env
        #- sed -i "s/:AUTH_SERVICE_HOST/$AUTH_SERVICE_HOST/g" app/.env
        # Upload to Production
        - export SSHPASS=$SSH_PASSWORD
        - GLOBIGNORE="image" sshpass -e scp -o stricthostkeychecking=no -r $(pwd) $SSH_USERNAME@159.65.125.31:/usr/src/ms_members/
        - sshpass -e ssh $SSH_USERNAME@159.65.125.31 'cd /usr/src/members_microservice; docker-compose down; cd /usr/src/; rm -rf members_microservice.old 2> /dev/null; mv members_microservice members_microservice.old && mv ms_members/sp-members-ms members_microservice; cd members_microservice; docker-compose up -d --build --force-recreate;'
    only: 
        - master